---

- name: MySQL Reposu yuklenir
  yum:
    name: http://repo.mysql.com/mysql57-community-release-el7-10.noarch.rpm
    state: present

- name: MySQL DAtabase ywklenir
  yum: name=mysql-server state=present
  
- name: MySQL-python yuklenir
  yum: name=MySQL-python state=present

- name: MySQL servisi enable ve start olunur
  service: name=mysqld state=started enabled=yes

- name: mysql ucun port  3306
  wait_for:
    host: 0.0.0.0
    port: 3306
    delay: 10
    state: drained

- set_fact:
   mysql_root_password: P@ss1234

- name: mysql ilk defe yazildiqda avtomatik teyin olunan root sifresi axtarilir
  shell: "echo `grep 'temporary.*root@localhost' /var/log/mysqld.log | sed 's/.*root@localhost: //'`"
  register: mysql_root_password_temp
  tags: register

- name: yeni root sifresi teyin edilir
  shell: 'mysql -e "SET PASSWORD = PASSWORD(''{{ mysql_root_password}}'');" --connect-expired-password -u root -p"{{ mysql_root_password_temp.stdout }}"'

